In [109]:
import pandas as pd
import numpy as np
df = pd.read_csv("data-logistic.csv", header = None, names = ['y', 'x1', 'x2'])
print(df.shape)
df.head(10)

(205, 3)


y        x1        x2
0 -1 -0.663827 -0.138526
1  1  1.994596  2.468025
2 -1 -1.247395  0.749425
3  1  2.309374  1.899836
4  1  0.849143  2.407750
5  1  1.454271 -0.665416
6  1  2.254227  2.263786
7 -1 -0.067580  1.469141
8 -1 -0.861961 -0.824856
9  1  0.699179  2.032488

In [237]:
w = np.ones(2) #weights vector, initialized with zeros
w_p = np.zeros(2) #weights vector of previous step
# to enter while cycle

#print(w[0])  
#print(w_p[0]) 
#print((w-w_p)[0])

l = df.shape[0] #number of records in training set
k = 1e-1 #step size
C = 10 #regularization constant
eps = 1e-5 #epsilon
while (np.sqrt(np.square((w - w_p)[0]) + np.square((w - w_p)[1])) > eps) and (i <= 10000):
    #print(w)
    #print(w_p)
    w_p = w.copy()
    sumL = np.zeros(2) # sum(L{M})
    for i in range(l):
        sumL[0] = sumL[0] + df['y'][i] * df['x1'][i] * (1 - 1 / (1 + np.exp(-df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
        sumL[1] = sumL[1] + df['y'][i] * df['x2'][i] * (1 - 1 / (1 + np.exp(-df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
    w[0] = w[0] + k / l * sumL[0] -  k * C * w[0]
    w[1] = w[1] + k / l * sumL[1] -  k * C * w[1]
    #print(w)
    #print(w_p)

print("iterations = ", i)    

a = np.zeros(l)
a = 1 / (1 + np.exp(-(w[0] * df['x1'] + w[1] * df['x2'])))

print(a[0:10])
#print(df.iloc[:,0])

iterations =  204
0    0.494402
1    0.529497
2    0.495737
3    0.528229
4    0.520967
5    0.506261
6    0.530084
7    0.508618
8    0.488737
9    0.517577
dtype: float64


In [140]:
from sklearn.metrics import roc_auc_score
print("AUC-ROC = ", roc_auc_score(df.iloc[:,0], a))

AUC-ROC =  0.936095238095


In [143]:
w = np.ones(2) #weights vector, initialized with zeros
w_p = np.zeros(2) #weights vector of previous step
# to enter while cycle

#print(w[0])  
#print(w_p[0]) 
#print((w-w_p)[0])

l = df.shape[0] #number of records in training set
k = 1e-1 #step size
C = 10 #regularization constant
eps = 1e-5 #epsilon
while (np.sqrt(np.square((w - w_p)[0]) + np.square((w - w_p)[1])) > eps) and (i <= 10000):
    #print(w)
    #print(w_p)
    w_p = w.copy()
    sumL = np.zeros(2) # sum(L{M})
    for i in range(0,l-1):
        sumL[0] = sumL[0] + df['y'][i] * df['x1'][i] * (1 / (1 + np.exp(df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
        sumL[1] = sumL[1] + df['y'][i] * df['x2'][i] * (1 / (1 + np.exp(df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
    w[0] = w[0] + k / l * sumL[0] -  k * C * w[0]
    w[1] = w[1] + k / l * sumL[1] -  k * C * w[1]
    #print(w)
    #print(w_p)

print("iterations = ", i)    

a = np.zeros(l)
a = 1 / (1 + np.exp(-(w[0] * df['x1'] + w[1] * df['x2'])))

print("a =\n", a[0:10])
#print(df.iloc[:,0])

from sklearn.metrics import roc_auc_score
print("AUC-ROC = ", roc_auc_score(df.iloc[:,0], a))

iterations =  203
a =
 0    0.494399
1    0.529602
2    0.495777
3    0.528306
4    0.521075
5    0.506223
6    0.530178
7    0.508687
8    0.488703
9    0.517668
dtype: float64
AUC-ROC =  0.936095238095


In [236]:
w = np.ones(2) #weights vector, initialized with zeros
w_p = np.zeros(2) #weights vector of previous step
# to enter while cycle

#print(w[0])  
#print(w_p[0]) 
#print((w-w_p)[0])

l = df.shape[0] #number of records in training set
k = 1e-1 #step size
C = 10 #regularization constant
eps = 1e-5 #epsilon
while (np.sqrt(np.square((w - w_p)[0]) + np.square((w - w_p)[1])) > eps) and (i <= 10000):
    #print(w)
    #print(w_p)
    w_p = w.copy()
    sumL = np.zeros(2) # sum(L{M})
    #print("sumL with loop:\n")
    #for i in range(l):
        #sumL[0] = sumL[0] + df['y'][i] * df['x1'][i] * (1 / (1 + np.exp(df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
        #sumL[1] = sumL[1] + df['y'][i] * df['x2'][i] * (1 / (1 + np.exp(df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
        #if (i<10):
        #    print(i, df['y'][i] * df['x1'][i] * 1 / (1 + np.exp(df['y'][i] * (w[0] * df['x1'][i] + w[1] * df['x2'][i]))))
    #print(sumL)
    sumL[0] = np.sum(np.multiply(df['y'], np.multiply(df['x1'], 1 / (1 + np.exp(np.multiply(df['y'], w[0] * df['x1'] + w[1] * df['x2']))))))
    sumL[1] = np.sum(np.multiply(df['y'], np.multiply(df['x2'], 1 / (1 + np.exp(np.multiply(df['y'], w[0] * df['x1'] + w[1] * df['x2']))))))
    #print(df['y'][0] * df['x1'][0] * 1 / (1 + np.exp(df['y'][0] * (w[0] * df['x1'][0] + w[1] * df['x2'][0]))))
    #print(df['y'][l-1] * df['x1'][l-1] * 1 / (1 + np.exp(df['y'][l-1] * (w[0] * df['x1'][l-1] + w[1] * df['x2'][l-1]))))
    #print("sumL without loop:\n")
    #SumL1 = np.multiply(df['y'], np.multiply(df['x1'], 1 / (1 + np.exp(np.multiply(df['y'], w[0] * df['x1'] + w[1] * df['x2'])))))
    #print(type(SumL1))
    #print(sumL) 
    #print(l-1)
    #print(np.shape(np.multiply(df['y'], np.multiply(df['x1'], 1 / (1 + np.exp(np.multiply(df['y'], w[0] * df['x1'] + w[1] * df['x2'])))))))
    #print(sumL)
    w = w + k / l * sumL -  k * C * w
    #w[1] = w[1] + k / l * sumL[1] -  k * C * w[1]
    #print(w)
    #print(w_p)

print("iterations = ", i)    

a = np.zeros(l)
a = 1 / (1 + np.exp(-(w[0] * df['x1'] + w[1] * df['x2'])))

print("a =\n", a[0:10])
#print(df.iloc[:,0])

from sklearn.metrics import roc_auc_score
print("AUC-ROC = ", roc_auc_score(df.iloc[:,0], a))

iterations =  204
a =
 0    0.494402
1    0.529497
2    0.495737
3    0.528229
4    0.520967
5    0.506261
6    0.530084
7    0.508618
8    0.488737
9    0.517577
dtype: float64
AUC-ROC =  0.936285714286


In [159]:
1 / (1 + 4 * np.ones(2))

array([ 0.2,  0.2])

In [233]:
np.random.seed(0)
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
for i in range(5):
    print(s[i])

1.76405234597
0.400157208367
0.978737984106
2.2408931992
1.86755799015
